[CI][Bench] Exit early in workflow if wrong perf runner is used

diff --git a/devops/actions/run-tests/benchmark/action.yml b/devops/actions/run-tests/benchmark/action.yml
--- a/devops/actions/run-tests/benchmark/action.yml
+++ b/devops/actions/run-tests/benchmark/action.yml
@@ -69,18 +69,13 @@ runs:
         '["BMG_PERF"]') GPU_TYPE="BMG" ;;
         '["TEST_PERF"]')
           # Benchmarks' framework test can be executed on any of the supported runners.
-          [ -z "$(printf '%s' "$RUNNER_NAME" | grep -o 'BMG')" ] && GPU_TYPE="BMG" || GPU_TYPE="PVC"
-          ;;
-        *)
-          # Best effort at matching if not known runners
-          # TODO: should we drop it and just exit instead?
-          GPU_TYPE="${RUNNER_TAG#[\"}"
-          GPU_TYPE="${GPU_TYPE%_PERF=\"]}"
-          echo "#"
-          echo "# WARNING: Only specific tuned runners are fully supported."
-          echo "# This workflow is not guaranteed to work with other runners."
-          echo "#" ;;
+          gpu_name=$(printf '%s' "$RUNNER_NAME" | grep -Eo 'BMG|PVC')
+          [ -n "$gpu_name" ] && GPU_TYPE="$gpu_name"
       esac
+      if [ -z "$GPU_TYPE" ]; then
+        echo "# ERROR: Only specific tuned runners are fully supported."
+        exit 1
+      fi
 
       case "$TARGET_DEVICE" in
         level_zero:*)
