Properly load repo/commit information in CI

diff --git a/devops/actions/run-tests/benchmark_v2/action.yml b/devops/actions/run-tests/benchmark_v2/action.yml
--- a/devops/actions/run-tests/benchmark_v2/action.yml
+++ b/devops/actions/run-tests/benchmark_v2/action.yml
@@ -110,6 +110,19 @@ runs:
       pip install --user --break-system-packages -r ./devops/scripts/benchmarks/requirements.txt
       echo "-----"
 
+      # clang builds have git repo / commit hashes in their --version output,
+      # same goes for dpcpp. Obtain git repo / commit hash info this way:
+
+      # First line of --version is formatted 'clang version ... (<repo> <commit>)'
+      # thus we parse for (<repo> <commit>):
+      sycl_git_info="$(clang++ --version | head -n 1 | grep -oE '\([^ ]+ [a-f0-9]+\)$')" | tr -d '()'
+      if [ -z "$sycl_git_info" ]; then
+        echo "Error: Unable to deduce SYCL build source repo/commit: Are you sure dpcpp variable is in PATH?"
+        exit 1
+      fi
+      sycl_git_repo="$(printf "$sycl_git_info" | cut -d' ' -f1)"
+      sycl_git_commit="$(printf "$sycl_git_info" | cut -d' ' -f2)"
+
       case "$ONEAPI_DEVICE_SELECTOR" in
         level_zero:*) SAVE_SUFFIX="L0" ;;
         level_zero_v2:*) SAVE_SUFFIX="L0v2" ;;
@@ -128,10 +141,13 @@ runs:
         --results-dir "./llvm-ci-perf-results/" \
         --output-dir "./llvm-ci-perf-results/" \
         --preset "$PRESET" \
-        --timestamp-override "$SAVE_TIMESTAMP"
+        # CI options:
+        --timestamp-override "$SAVE_TIMESTAMP" \
+        --sycl-github-repo "$sycl_git_repo" \ 
+        --sycl-commit "$sycl_git_commit"
       echo "-----"
       python3 ./devops/scripts/benchmarks/compare.py to_hist \
-        --name Baseline_PVC_L0 \
+        --name "$SAVE_NAME" \
         --compare-file "./llvm-ci-perf-results/results/${SAVE_NAME}_${SAVE_TIMESTAMP}.json" \
         --results-dir "./llvm-ci-perf-results/results/"
 
