Failing e2e tests no longer kill the whole build

diff --git a/.github/workflows/e2e_core.yml b/.github/workflows/e2e_core.yml
--- a/.github/workflows/e2e_core.yml
+++ b/.github/workflows/e2e_core.yml
@@ -190,7 +190,7 @@ jobs:
 
     - name: Run e2e tests
       id: tests
-      run: ninja -C build-e2e check-sycl-e2e
+      run: ninja -C build-e2e check-sycl-e2e || echo "e2e tests have failed. Ignoring failure."
 
     # FIXME: Requires pull-request: write permissions but this is only granted
     # on pull requests from forks if using pull_request_target workflow
