TBD

diff --git a/.github/workflows/sycl-linux-precommit.yml b/.github/workflows/sycl-linux-precommit.yml
--- a/.github/workflows/sycl-linux-precommit.yml
+++ b/.github/workflows/sycl-linux-precommit.yml
@@ -59,192 +59,223 @@ jobs:
       changes: ${{ needs.detect_changes.outputs.filters }}
 
       toolchain_artifact: sycl_linux_default
-      e2e_binaries_artifact: e2e_bin
-      e2e_binaries_preview_artifact: e2e_bin_preview
-
-  # If a PR changes CUDA adapter, run the build on Ubuntu 22.04 as well.
-  # Ubuntu 22.04 container has CUDA 12.1 installed while Ubuntu 24.0 image
-  # has CUDA 12.6.1 installed.
-  # The idea is to ensure that the code works with both CUDA versions.
-  build_ubuntu2204:
-    needs: [detect_changes]
-    if: always() && !cancelled() && contains(needs.detect_changes.outputs.filters, 'ur_cuda_adapter')
-    uses: ./.github/workflows/sycl-linux-build.yml
-    with:
-      build_ref: ${{ github.sha }}
-      build_cache_root: "/__w/"
-      build_cache_suffix: "ubuntu22"
-      build_image: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
-      changes: ${{ needs.detect_changes.outputs.filters }}
-
-      toolchain_artifact: sycl_linux_ubuntu22
-
-  compat_read_exclude:
-    name: Read compatibility testing exclude list
-    runs-on: [Linux, aux-tasks]
-    outputs:
-      FILTER_6_2: ${{ steps.result.outputs.FILTER_6_2 }}
-      FILTER_6_3: ${{ steps.result.outputs.FILTER_6_3 }}
+      # e2e_binaries_artifact: e2e_bin
+      # e2e_binaries_preview_artifact: e2e_bin_preview
+  build_run_native_cpu_e2e_tests:
+    runs-on: [Linux, build]
+    needs: [build]
     steps:
-    - uses: actions/checkout@v4
-      with:
-        sparse-checkout: |
-          devops/
-    - name: Register cleanup after job is finished
-      uses: ./devops/actions/cleanup
-    - id: result
-      shell: bash
-      run: |
-        # Transform to format expected by `llvm-lit --filter-out "pattern1|pattern2|..."`.
-        # First, remove comments/empty lines, then join lines with "|" as separator.
-        echo FILTER_6_2="$(grep -v '^#\|^\W*$' devops/compat_ci_exclude.sycl-rel-6_2 | paste -sd '|')" >> $GITHUB_OUTPUT
-        echo FILTER_6_3="$(grep -v '^#\|^\W*$' devops/compat_ci_exclude.sycl-rel-6_3 | paste -sd '|')" >> $GITHUB_OUTPUT
+      - uses: actions/checkout@v4
+        with:
+          sparse-checkout: |
+            devops/
 
-  run_prebuilt_e2e_tests:
-    needs: [build, detect_changes, compat_read_exclude]
-    if: ${{ always() && !cancelled() && needs.build.outputs.build_conclusion == 'success' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: GEN 12 Integrated
-            runner: '["Linux", "gen12"]'
-            target_devices: native_cpu:cpu;level_zero:gpu;opencl:gpu;opencl:cpu
-          - name: NVIDIA/CUDA
-            runner: '["Linux", "cuda"]'
-            image_options: -u 1001 --gpus all --cap-add SYS_ADMIN
-            target_devices: cuda:gpu
-          - name: AMD/HIP
-            runner: '["Linux", "amdgpu"]'
-            image_options: -u 1001 --device=/dev/dri --device=/dev/kfd
-            target_devices: hip:gpu
-            extra_lit_opts: -j 1
-          - name: Intel Arc A-Series Graphics
-            runner: '["Linux", "arc"]'
-            target_devices: level_zero:gpu;opencl:gpu;level_zero_v2:gpu
-          - name: Dev IGC / Intel Arc A-Series Graphics
-            runner: '["Linux", "arc"]'
-            image: ghcr.io/intel/llvm/ubuntu2404_intel_drivers:devigc
-            target_devices: level_zero:gpu
-            use_igc_dev: true
-            env: '{"LIT_FILTER":"Matrix/"}'
-          - name: Intel Ponte Vecchio GPU
-            runner: '["Linux", "pvc"]'
-            target_devices: level_zero:gpu;opencl:gpu;level_zero_v2:gpu
-          - name: Dev IGC / Intel Ponte Vecchio GPU
-            runner: '["Linux", "pvc"]'
-            image: ghcr.io/intel/llvm/ubuntu2404_intel_drivers:devigc
-            target_devices: level_zero:gpu
-            use_igc_dev: true
-            env: '{"LIT_FILTER":"Matrix/"}'
-          - name: Intel Battlemage Graphics
-            runner: '["Linux", "bmg"]'
-            target_devices: level_zero_v1:gpu;level_zero_v2:gpu
-          - name: Preview Mode
-            runner: '["Linux", "gen12"]'
-            target_devices: level_zero:gpu;opencl:gpu;opencl:cpu
-            extra_lit_opts: --param test-preview-mode=True
-            e2e_binaries_artifact: e2e_bin_preview
-          - name: ABI compatibility against sycl-rel-6_2
-            runner: '["Linux", "pvc"]'
-            image: ghcr.io/intel/llvm/sycl_prebuilt_tests:sycl-rel-6_2
-            target_devices: level_zero:gpu
-            extra_lit_opts: '--param test-preview-mode=False --filter-out "${{ needs.compat_read_exclude.outputs.FILTER_6_2 }}"'
-            e2e_binaries_artifact: 'in-container'
-          - name: ABI compatibility against sycl-rel-6_3
-            runner: '["Linux", "pvc"]'
-            image: ghcr.io/intel/llvm/sycl_prebuilt_tests:sycl-rel-6_3
-            target_devices: level_zero:gpu
-            extra_lit_opts: '--param test-preview-mode=False --filter-out "${{ needs.compat_read_exclude.outputs.FILTER_6_3 }}"'
-            e2e_binaries_artifact: 'in-container'
+      # download build artefact
+      - name: Download toolchain
+        uses: actions/download-artifact@v4
+        with:
+          name: sycl_linux_default
+      - name: Extract SYCL toolchain
+        shell: bash
+        run: |
+          mkdir toolchain
+          ls
+          tar -xf llvm_sycl.tar.zst -C toolchain
+          rm llvm_sycl.tar.zst
+      - name: Build and run E2E tests
+        uses: ./devops/actions/run-tests/e2e
+        with:
+          ref: ${{ inputs.ref || github.sha }}
+          testing_mode: build-only
+          target_devices: all
+          sycl_compiler: $GITHUB_WORKSPACE/toolchain/bin/clang++
+          extra_lit_opts: --param sycl_build_targets="native_cpu"
+          extra_cmake_args: -DSYCL_TEST_E2E_TARGETS="native_cpu:cpu"
 
-    uses: ./.github/workflows/sycl-linux-run-tests.yml
-    with:
-      name: ${{ matrix.name }}
-      runner: ${{ matrix.runner }}
-      image: ${{ matrix.image }}
-      image_options: ${{ matrix.image_options || '-u 1001 --device=/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --privileged --cap-add SYS_ADMIN' }}
-      target_devices: ${{ matrix.target_devices }}
-      extra_lit_opts: ${{ matrix.extra_lit_opts }}
-      repo_ref: ${{ github.sha }}
-      toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
-      toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
-      toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
-      e2e_binaries_artifact: ${{ matrix.e2e_binaries_artifact || 'e2e_bin' }}
-      e2e_testing_mode: 'run-only'
+        
+  # # If a PR changes CUDA adapter, run the build on Ubuntu 22.04 as well.
+  # # Ubuntu 22.04 container has CUDA 12.1 installed while Ubuntu 24.0 image
+  # # has CUDA 12.6.1 installed.
+  # # The idea is to ensure that the code works with both CUDA versions.
+  # build_ubuntu2204:
+  #   needs: [detect_changes]
+  #   if: always() && !cancelled() && contains(needs.detect_changes.outputs.filters, 'ur_cuda_adapter')
+  #   uses: ./.github/workflows/sycl-linux-build.yml
+  #   with:
+  #     build_ref: ${{ github.sha }}
+  #     build_cache_root: "/__w/"
+  #     build_cache_suffix: "ubuntu22"
+  #     build_image: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
+  #     changes: ${{ needs.detect_changes.outputs.filters }}
 
-      # Do not install drivers on AMD and CUDA runners.
-      install_igc_driver: >-
-        ${{ !contains(matrix.target_devices, 'cuda') &&
-        !contains(matrix.target_devices, 'hip') &&
-        contains(needs.detect_changes.outputs.filters, 'drivers') }}
-      install_dev_igc_driver: >-
-        ${{ !contains(matrix.target_devices, 'cuda') &&
-        !contains(matrix.target_devices, 'hip') &&
-        matrix.use_igc_dev &&
-        (contains(needs.detect_changes.outputs.filters, 'devigccfg') || contains(needs.detect_changes.outputs.filters, 'drivers')) ||
-        'false' }}
-      # Run only if the PR does not have the 'ci-no-devigc' label.
-      skip_run: ${{matrix.use_igc_dev && contains(github.event.pull_request.labels.*.name, 'ci-no-devigc') || 'false'}}
-      env: ${{ matrix.env || (contains(needs.detect_changes.outputs.filters, 'esimd') && '{}' || '{"LIT_FILTER_OUT":"ESIMD/"}') }}
+  #     toolchain_artifact: sycl_linux_ubuntu22
 
-  test_benchmark_scripts:
-    needs: [build, detect_changes]
-    if: |
-      always() && !cancelled()
-      && needs.build.outputs.build_conclusion == 'success'
-      && contains(needs.detect_changes.outputs.filters, 'benchmarks')
-    uses: ./.github/workflows/sycl-linux-run-tests.yml
-    with:
-      name: Benchmark suite precommit testing
-      runner: '["PVC_PERF"]'
-      image: ghcr.io/intel/llvm/sycl_ubuntu2404_nightly:latest
-      image_options: -u 1001 --device=/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --privileged --cap-add SYS_ADMIN
-      target_devices: 'level_zero:gpu'
-      tests_selector: benchmarks
-      benchmark_upload_results: false
-      benchmark_preset: 'Minimal'
-      benchmark_dry_run: true
-      repo_ref: ${{ github.sha }}
-      toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
-      toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
-      toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
+  # compat_read_exclude:
+  #   name: Read compatibility testing exclude list
+  #   runs-on: [Linux, aux-tasks]
+  #   outputs:
+  #     FILTER_6_2: ${{ steps.result.outputs.FILTER_6_2 }}
+  #     FILTER_6_3: ${{ steps.result.outputs.FILTER_6_3 }}
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       sparse-checkout: |
+  #         devops/
+  #   - name: Register cleanup after job is finished
+  #     uses: ./devops/actions/cleanup
+  #   - id: result
+  #     shell: bash
+  #     run: |
+  #       # Transform to format expected by `llvm-lit --filter-out "pattern1|pattern2|..."`.
+  #       # First, remove comments/empty lines, then join lines with "|" as separator.
+  #       echo FILTER_6_2="$(grep -v '^#\|^\W*$' devops/compat_ci_exclude.sycl-rel-6_2 | paste -sd '|')" >> $GITHUB_OUTPUT
+  #       echo FILTER_6_3="$(grep -v '^#\|^\W*$' devops/compat_ci_exclude.sycl-rel-6_3 | paste -sd '|')" >> $GITHUB_OUTPUT
 
-  test-perf:
-    needs: [build, detect_changes]
-    if: |
-      always() && !cancelled()
-      && needs.build.outputs.build_conclusion == 'success'
-      && (contains(github.event.pull_request.labels.*.name, 'run-perf-tests')
-          || contains(needs.detect_changes.outputs.filters, 'perf-tests'))
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: Intel GEN12 Graphics system
-            runner: '["Linux", "gen12"]'
-            image_extra_opts: --device=/dev/dri
-          - name: Intel Arc A-Series Graphics system
-            runner: '["Linux", "arc"]'
-            image_extra_opts: --device=/dev/dri
-          - name: AMD system
-            runner: '["Linux", "amdgpu"]'
-            image_extra_opts: --device=/dev/dri --device=/dev/kfd
-          - name: CUDA system
-            runner: '["Linux", "cuda"]'
-            image_extra_opts: --gpus all
-    uses: ./.github/workflows/sycl-linux-run-tests.yml
-    with:
-      name: Perf tests on ${{ matrix.name }}
-      runner: ${{ matrix. runner }}
-      image_options: -u 1001 --privileged --cap-add SYS_ADMIN ${{ matrix.image_extra_opts }}
-      target_devices: all
+  # run_prebuilt_e2e_tests:
+  #   needs: [build, detect_changes, compat_read_exclude]
+  #   if: ${{ always() && !cancelled() && needs.build.outputs.build_conclusion == 'success' }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: GEN 12 Integrated
+  #           runner: '["Linux", "gen12"]'
+  #           target_devices: level_zero:gpu;opencl:gpu;opencl:cpu
+  #         - name: NVIDIA/CUDA
+  #           runner: '["Linux", "cuda"]'
+  #           image_options: -u 1001 --gpus all --cap-add SYS_ADMIN
+  #           target_devices: cuda:gpu
+  #         - name: AMD/HIP
+  #           runner: '["Linux", "amdgpu"]'
+  #           image_options: -u 1001 --device=/dev/dri --device=/dev/kfd
+  #           target_devices: hip:gpu
+  #           extra_lit_opts: -j 1
+  #         - name: Intel Arc A-Series Graphics
+  #           runner: '["Linux", "arc"]'
+  #           target_devices: level_zero:gpu;opencl:gpu;level_zero_v2:gpu
+  #         - name: Dev IGC / Intel Arc A-Series Graphics
+  #           runner: '["Linux", "arc"]'
+  #           image: ghcr.io/intel/llvm/ubuntu2404_intel_drivers:devigc
+  #           target_devices: level_zero:gpu
+  #           use_igc_dev: true
+  #           env: '{"LIT_FILTER":"Matrix/"}'
+  #         - name: Intel Ponte Vecchio GPU
+  #           runner: '["Linux", "pvc"]'
+  #           target_devices: level_zero:gpu;opencl:gpu;level_zero_v2:gpu
+  #         - name: Dev IGC / Intel Ponte Vecchio GPU
+  #           runner: '["Linux", "pvc"]'
+  #           image: ghcr.io/intel/llvm/ubuntu2404_intel_drivers:devigc
+  #           target_devices: level_zero:gpu
+  #           use_igc_dev: true
+  #           env: '{"LIT_FILTER":"Matrix/"}'
+  #         - name: Intel Battlemage Graphics
+  #           runner: '["Linux", "bmg"]'
+  #           target_devices: level_zero_v1:gpu;level_zero_v2:gpu
+  #         - name: Preview Mode
+  #           runner: '["Linux", "gen12"]'
+  #           target_devices: level_zero:gpu;opencl:gpu;opencl:cpu
+  #           extra_lit_opts: --param test-preview-mode=True
+  #           e2e_binaries_artifact: e2e_bin_preview
+  #         - name: ABI compatibility against sycl-rel-6_2
+  #           runner: '["Linux", "pvc"]'
+  #           image: ghcr.io/intel/llvm/sycl_prebuilt_tests:sycl-rel-6_2
+  #           target_devices: level_zero:gpu
+  #           extra_lit_opts: '--param test-preview-mode=False --filter-out "${{ needs.compat_read_exclude.outputs.FILTER_6_2 }}"'
+  #           e2e_binaries_artifact: 'in-container'
+  #         - name: ABI compatibility against sycl-rel-6_3
+  #           runner: '["Linux", "pvc"]'
+  #           image: ghcr.io/intel/llvm/sycl_prebuilt_tests:sycl-rel-6_3
+  #           target_devices: level_zero:gpu
+  #           extra_lit_opts: '--param test-preview-mode=False --filter-out "${{ needs.compat_read_exclude.outputs.FILTER_6_3 }}"'
+  #           e2e_binaries_artifact: 'in-container'
 
-      env: '{"LIT_FILTER":"PerformanceTests/"}'
-      extra_lit_opts: -a -j 1 --param enable-perf-tests=True
+  #   uses: ./.github/workflows/sycl-linux-run-tests.yml
+  #   with:
+  #     name: ${{ matrix.name }}
+  #     runner: ${{ matrix.runner }}
+  #     image: ${{ matrix.image }}
+  #     image_options: ${{ matrix.image_options || '-u 1001 --device=/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --privileged --cap-add SYS_ADMIN' }}
+  #     target_devices: ${{ matrix.target_devices }}
+  #     extra_lit_opts: ${{ matrix.extra_lit_opts }}
+  #     repo_ref: ${{ github.sha }}
+  #     toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
+  #     toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
+  #     toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
+  #     e2e_binaries_artifact: ${{ matrix.e2e_binaries_artifact || 'e2e_bin' }}
+  #     e2e_testing_mode: 'run-only'
 
-      repo_ref: ${{ github.sha }}
+  #     # Do not install drivers on AMD and CUDA runners.
+  #     install_igc_driver: >-
+  #       ${{ !contains(matrix.target_devices, 'cuda') &&
+  #       !contains(matrix.target_devices, 'hip') &&
+  #       contains(needs.detect_changes.outputs.filters, 'drivers') }}
+  #     install_dev_igc_driver: >-
+  #       ${{ !contains(matrix.target_devices, 'cuda') &&
+  #       !contains(matrix.target_devices, 'hip') &&
+  #       matrix.use_igc_dev &&
+  #       (contains(needs.detect_changes.outputs.filters, 'devigccfg') || contains(needs.detect_changes.outputs.filters, 'drivers')) ||
+  #       'false' }}
+  #     # Run only if the PR does not have the 'ci-no-devigc' label.
+  #     skip_run: ${{matrix.use_igc_dev && contains(github.event.pull_request.labels.*.name, 'ci-no-devigc') || 'false'}}
+  #     env: ${{ matrix.env || (contains(needs.detect_changes.outputs.filters, 'esimd') && '{}' || '{"LIT_FILTER_OUT":"ESIMD/"}') }}
 
-      toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
-      toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
-      toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
+  # test_benchmark_scripts:
+  #   needs: [build, detect_changes]
+  #   if: |
+  #     always() && !cancelled()
+  #     && needs.build.outputs.build_conclusion == 'success'
+  #     && contains(needs.detect_changes.outputs.filters, 'benchmarks')
+  #   uses: ./.github/workflows/sycl-linux-run-tests.yml
+  #   with:
+  #     name: Benchmark suite precommit testing
+  #     runner: '["PVC_PERF"]'
+  #     image: ghcr.io/intel/llvm/sycl_ubuntu2404_nightly:latest
+  #     image_options: -u 1001 --device=/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --privileged --cap-add SYS_ADMIN
+  #     target_devices: 'level_zero:gpu'
+  #     tests_selector: benchmarks
+  #     benchmark_upload_results: false
+  #     benchmark_preset: 'Minimal'
+  #     benchmark_dry_run: true
+  #     repo_ref: ${{ github.sha }}
+  #     toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
+  #     toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
+  #     toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
+
+  # test-perf:
+  #   needs: [build, detect_changes]
+  #   if: |
+  #     always() && !cancelled()
+  #     && needs.build.outputs.build_conclusion == 'success'
+  #     && (contains(github.event.pull_request.labels.*.name, 'run-perf-tests')
+  #         || contains(needs.detect_changes.outputs.filters, 'perf-tests'))
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: Intel GEN12 Graphics system
+  #           runner: '["Linux", "gen12"]'
+  #           image_extra_opts: --device=/dev/dri
+  #         - name: Intel Arc A-Series Graphics system
+  #           runner: '["Linux", "arc"]'
+  #           image_extra_opts: --device=/dev/dri
+  #         - name: AMD system
+  #           runner: '["Linux", "amdgpu"]'
+  #           image_extra_opts: --device=/dev/dri --device=/dev/kfd
+  #         - name: CUDA system
+  #           runner: '["Linux", "cuda"]'
+  #           image_extra_opts: --gpus all
+  #   uses: ./.github/workflows/sycl-linux-run-tests.yml
+  #   with:
+  #     name: Perf tests on ${{ matrix.name }}
+  #     runner: ${{ matrix. runner }}
+  #     image_options: -u 1001 --privileged --cap-add SYS_ADMIN ${{ matrix.image_extra_opts }}
+  #     target_devices: all
+
+  #     env: '{"LIT_FILTER":"PerformanceTests/"}'
+  #     extra_lit_opts: -a -j 1 --param enable-perf-tests=True
+
+  #     repo_ref: ${{ github.sha }}
+
+  #     toolchain_artifact: ${{ needs.build.outputs.toolchain_artifact }}
+  #     toolchain_artifact_filename: ${{ needs.build.outputs.toolchain_artifact_filename }}
+  #     toolchain_decompress_command: ${{ needs.build.outputs.toolchain_decompress_command }}
