[CI] Improve SYCL-CTS job
1. Extend the number of suites.
2. Add the ability to define ninja's extra args for build-cts.
3. Keep executing the loop if suite fails.

diff --git a/.github/workflows/sycl-linux-run-tests.yml b/.github/workflows/sycl-linux-run-tests.yml
--- a/.github/workflows/sycl-linux-run-tests.yml
+++ b/.github/workflows/sycl-linux-run-tests.yml
@@ -26,6 +26,9 @@ on:
           if inputs.target_devices contains 'ext_oneapi_hip'
         type: string
         required: False
+      ninja_build_cts_extra_args:
+        type: string
+        required: False
       tests_selector:
         description: |
           Two possible options: "e2e" and "cts".
@@ -104,6 +107,8 @@ on:
           - 'opencl:fpga'
           - 'ext_oneapi_level_zero:gpu'
           - 'ext_oneapi_hip:gpu'
+      ninja_build_cts_extra_args:
+        type: string
       tests_selector:
         type: choice
         options:
@@ -278,6 +283,7 @@ jobs:
       if: inputs.tests_selector == 'cts'
       env:
         CMAKE_EXTRA_ARGS: ${{ inputs.extra_cmake_args }}
+        NINJA_BUILD_CTS_EXTRA_ARGS: ${{ inputs.ninja_build_cts_extra_args }}
       run: |
         cmake -GNinja -B./build-cts -S./khronos_sycl_cts -DCMAKE_CXX_COMPILER=$(which clang++) \
         -DSYCL_IMPLEMENTATION=DPCPP \
@@ -286,7 +292,7 @@ jobs:
         -DSYCL_CTS_MEASURE_BUILD_TIMES=ON \
         -DDPCPP_INSTALL_DIR="$$(dirname (which clang++))/.." \
         $CMAKE_EXTRA_ARGS
-        ninja -C build-cts
+        ninja -C build-cts $NINJA_BUILD_CTS_EXTRA_ARGS
 
     - name: SYCL CTS List devices
       if: inputs.tests_selector == 'cts'
@@ -297,6 +303,13 @@ jobs:
       if: inputs.tests_selector == 'cts'
       env:
         ONEAPI_DEVICE_SELECTOR: ${{ inputs.target_devices }}
+      # By-default GitHub actions execute the "run" shell script with -e option,
+      # so the execution terminates if any command returns a non-zero status.
+      # Since we're using a loop to run all test-binaries separately, some test
+      # may fail and terminate the execution. Setting "shell" value to override
+      # the default behavior.
+      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#custom-shell
+      shell: bash {0}
       # FIXME: For some reason the "sub_group api" test-case is failing with
       # SIGSEGV while running test_all, so running each binary separately.
       # BTW test_all requires a lot of resources to build it, so probably it'll
@@ -304,10 +317,25 @@ jobs:
       # run: |
       #   ./build-cts/bin/test_all $CTS_TEST_ARGS
       run: |
+        status=""
+        failed_suites=""
         for i in `ls -1 ./build-cts/bin`; do
           if [ "$i" != "test_all" ]; then
             echo "::group::Running $i"
             build-cts/bin/$i
+            if [ $? -ne 0 ]; then
+              status=1
+              if [$failed_suites == ""]; then
+                failed_suites=$i
+              else
+                failed_suites="$failed_suites, $i"
+              fi
+            fi
             echo "::endgroup::"
           fi
         done
+        if [ -n "$status" ]; then
+          echo "Failed suite(s): $failed_suites"
+          exit 1
+        fi
+        exit 0
